//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MessagingWebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MessagingDBMessages : DbContext
    {
        public MessagingDBMessages()
            : base("name=MessagingDBMessages")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            //Fluent Api
            //modelBuilder.Entity<Message>()
              //  .HasRequired<User>(u => u.User)
               // .WithMany(s => s.StudentAddress)
               // .HasForeignKey(s => s.StudentId);
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Message> Messages { get; set; }
    }
}
